school-event-management-system/school_event_management_system/config/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from main.views import BadRequestView, PageNotFoundView, PermissionDeniedView, ServerErrorView

handler400 = BadRequestView.as_view()
handler403 = PermissionDeniedView.as_view()
handler404 = PageNotFoundView.as_view()
handler500 = ServerErrorView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls')),
    path('', include('events.urls')),
    path('', include('main.urls')),
    path('', include('mailings.urls')),

    path('', RedirectView.as_view(url='/events/', permanent=True)),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

school-event-management-system/school_event_management_system/events/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from events.views import (
    DiplomasListView,
    EditParticipantEventView,
    EventArchiveView,
    EventDetailView,
    EventListView,
    EventQRCodeView,
    EventSolutionView,
    ParticipantEventsView,
    RegisterOnEventView,
    SupervisorEventsView,
    export_event_participants,
)

urlpatterns = [
    path(
        route='events/',
        view=EventListView.as_view(),
        name='events_list',
    ),
    path(
        route='events/participant/',
        view=ParticipantEventsView.as_view(),
        name='participant_events',
    ),
    path(
        route='events/supervisor/',
        view=SupervisorEventsView.as_view(),
        name='supervisor_events',
    ),
    path(
        route='events/archive/',
        view=EventArchiveView.as_view(),
        name='events_archive',
    ),
    path(
        route='event/<slug:slug>/',
        view=EventDetailView.as_view(),
        name='event_detail',
    ),
    path(
        route='event/<slug:slug>/qr_code/',
        view=EventQRCodeView.as_view(),
        name='event_qr_code',
    ),
    path(
        route='event/<slug:slug>/register/',
        view=login_required(
            RegisterOnEventView.as_view(),
        ),
        name='register_on_event',
    ),
    path(
        route='event/<slug:slug>/edit/',
        view=login_required(
            EditParticipantEventView.as_view(),
        ),
        name='edit_participant_event',
    ),
    path(
        route='event/<slug:slug>/solution/',
        view=login_required(
            EventSolutionView.as_view(),
        ),
        name='event_solution',
    ),
    path(
        route='event/<slug:slug>/export_participants/',
        view=export_event_participants,
        name='export_event_participants',
    ),
    # diplomas
    path(
        route='diplomas/',
        view=DiplomasListView.as_view(),
        name='diplomas_list',
    ),
]

school-event-management-system/school_event_management_system/main/urls.py
from django.urls import path

from main.views import SitemapView

urlpatterns = [
    path(
        route='sitemap/',
        view=SitemapView.as_view(),
        name='site_map',
    ),
]

school-event-management-system/school_event_management_system/events/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from phonenumber_field.modelfields import PhoneNumberField

from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from accounts.models import User


def get_event_image_upload_path(instance: 'Event', filename: str) -> str:
    return f'upload/{instance.name}/{filename}'


def get_event_regulations_upload_path(instance: 'Event', filename: str) -> str:
    return f'upload/{instance.name}/{filename}'


def get_event_results_upload_path(instance: 'Event', filename: str) -> str:
    return f'upload/{instance.name}/{filename}'


class EventStatusChoices(models.TextChoices):
    REGISTRATION_PENDING = 'Ожидание регистрации', 'Ожидание регистрации'
    REGISTRATION_OPEN = 'Регистрация открыта', 'Регистрация открыта'
    ONGOING = 'В процессе', 'В процессе'
    COMPLETED = 'Завершено', 'Завершено'
    CANCELLED = 'Отменено', 'Отменено'
    POSTPONED = 'Отложено', 'Отложено'


class EventTypeChoices(models.TextChoices):
    INDIVIDUAL = 'Индивидуальное', 'Индивидуальное'
    INDIVIDUAL_AND_COLLECTIVE = 'Индивидуальное, коллективное', 'Индивидуальное, коллективное'
    TEAM = 'Командное', 'Командное'
    CLASS_TEAMS = 'Командное от классов', 'Командное от классов'


class EventStageChoices(models.TextChoices):
    SCHOOL = 'Школьный', 'Школьный'
    DISTRICT = 'Районный', 'Районный'
    CITY = 'Городской', 'Городской'
    REGIONAL = 'Региональный', 'Региональный'
    NATIONAL = 'Всероссийский', 'Всероссийский'
    INTERNATIONAL = 'Международный', 'Международный'


class Event(models.Model):
    image = models.ImageField(
        verbose_name=_('изображение предварительного просмотра мероприятия'),
        blank=True,
        null=True,
        upload_to=get_event_image_upload_path,
    )
    name = models.CharField(
        verbose_name=_('название мероприятия'),
        max_length=100,
        unique=True,
    )
    slug = models.SlugField(
        verbose_name=_('url мероприятия'),
        max_length=100,
        unique=True,
    )
    description = RichTextUploadingField(
        verbose_name=_('описание мероприятия'),
        blank=True,
        null=True,
    )

    need_presentation = models.BooleanField(
        verbose_name=_('нужна презентация'),
        blank=True,
        default=False,
    )

    regulations = models.FileField(
        verbose_name=_('регламент мероприятия'),
        blank=True,
        null=True,
        upload_to=get_event_regulations_upload_path,
    )
    results = models.FileField(
        verbose_name=_('итоги мероприятия'),
        blank=True,
        null=True,
        upload_to=get_event_results_upload_path,
    )

    maximum_number_of_team_members = models.IntegerField(
        verbose_name=_('максимальное количество участников в команде'),
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100),
        ],
        blank=True,
        null=True,
        default=1,
    )
    minimum_number_of_team_members = models.IntegerField(
        verbose_name=_('минимальное количество участников в команде'),
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100),
        ],
        blank=True,
        null=True,
        default=1,
    )

    status = models.CharField(
        verbose_name=_('статус мероприятия'),
        blank=True,
        max_length=50,
        choices=EventStatusChoices.choices,
    )
    type = models.CharField(
        verbose_name=_('тип мероприятия'),
        blank=True,
        max_length=50,
        choices=EventTypeChoices.choices,
    )
    stage = models.CharField(
        verbose_name=_('уровень мероприятия'),
        blank=True,
        max_length=50,
        choices=EventStageChoices.choices,
        default=EventStageChoices.SCHOOL,
    )

    date_of_starting_registration = models.DateField(
        verbose_name=_('дата начала регистрации'),
        blank=True,
        null=True,
    )
    date_of_ending_registration = models.DateField(
        verbose_name=_('дата окончания регистрации'),
        blank=True,
        null=True,
    )
    date_of_starting_event = models.DateField(
        verbose_name=_('дата начала мероприятия'),
        blank=True,
        null=True,
    )

    need_account = models.BooleanField(
        verbose_name=_('нужен аккаунт у участников'),
        blank=True,
        default=True,
    )

    published = models.BooleanField(
        verbose_name=_('является ли опубликованным'),
        blank=True,
        default=False,
    )
    archived = models.BooleanField(
        verbose_name=_('находится в архиве'),
        blank=True,
        default=False,
    )

    class Meta:
        verbose_name = _('мероприятие')
        verbose_name_plural = _('мероприятия')

    def __str__(self):
        return self.name


class Team(models.Model):
    event = models.ForeignKey(
        Event,
        verbose_name=_('мероприятие'),
        on_delete=models.CASCADE,
        related_name='teams',
    )
    supervisor = models.ForeignKey(
        User,
        verbose_name=_('руководитель'),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    supervisor_fio = models.CharField(
        verbose_name=_('ФИО руководителя'),
        max_length=255,
        blank=True,
    )
    supervisor_phone_number = PhoneNumberField(
        verbose_name=_('номер телефона руководителя'),
        blank=True,
        validators=[
            RegexValidator(
                regex=r'^\+?[0-9]{7,15}$',
                message='Номер телефона необходимо ввести в формате: +XXXXXXXXXXXXX.',
            ),
        ],
    )
    supervisor_email = models.EmailField(
        verbose_name=_('почта руководителя'),
        max_length=60,
        blank=True,
    )
    name = models.CharField(
        verbose_name=_('название команды'),
        max_length=100,
    )
    school_class = models.CharField(
        verbose_name=_('класс который представляет команда'),
        max_length=5,
        blank=True,
    )

    class Meta:
        verbose_name = _('команда')
        verbose_name_plural = _('команды')

    def __str__(self):
        return f'{self.name}'


class Participant(models.Model):
    event = models.ForeignKey(
        Event,
        verbose_name=_('мероприятие'),
        on_delete=models.CASCADE,
        related_name='participants',
    )
    user = models.ForeignKey(
        User,
        verbose_name=_('пользователь'),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='participant',
    )
    fio = models.CharField(
        verbose_name=_('ФИО ученика'),
        max_length=255,
        blank=True,
    )
    team = models.ForeignKey(
        Team,
        verbose_name=_('команда'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='participants',
    )
    supervisor = models.ForeignKey(
        User,
        verbose_name=_('руководитель'),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='supervised_participants',
    )
    supervisor_fio = models.CharField(
        verbose_name=_('ФИО руководителя'),
        max_length=255,
        blank=True,
    )
    supervisor_phone_number = PhoneNumberField(
        verbose_name=_('номер телефона руководителя'),
        blank=True,
        validators=[
            RegexValidator(
                regex=r'^\+?[0-9]{7,15}$',
                message='Номер телефона необходимо ввести в формате: +XXXXXXXXXXXXX.',
            ),
        ],
    )
    supervisor_email = models.EmailField(
        verbose_name=_('почта руководителя'),
        max_length=60,
        blank=True,
    )

    class Meta:
        verbose_name = _('участник')
        verbose_name_plural = _('участники')

    def __str__(self):
        if self.user:
            return f'{self.user} {self.event}'
        else:
            return f'{self.fio} {self.event}'


class EventDiplomas(models.Model):
    event = models.ForeignKey(
        Event,
        verbose_name=_('мероприятие'),
        on_delete=models.CASCADE,
    )
    url = models.URLField(
        verbose_name=_('ссылка на дипломы'),
    )

    class Meta:
        verbose_name = _('Дипломы мероприятия')
        verbose_name_plural = _('Дипломы мероприятий')

    def __str__(self):
        return f'{self.event}'


class Solution(models.Model):
    event = models.ForeignKey(
        Event,
        verbose_name=_('мероприятие'),
        on_delete=models.CASCADE,
    )
    participant = models.ForeignKey(
        Participant,
        verbose_name=_('участник'),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    team = models.ForeignKey(
        Team,
        verbose_name=_('команда'),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    subject = models.CharField(
        verbose_name=_('предмет'),
        max_length=255,
    )
    theses = models.CharField(
        verbose_name=_('краткие тезисы'),
        max_length=5120,
        blank=True,
    )
    topic = models.CharField(
        verbose_name=_('тема проекта'),
        max_length=255,
    )
    url = models.URLField(
        verbose_name=_('ссылка на файлы'),
        blank=True,
    )

    class Meta:
        verbose_name = _('Работа')
        verbose_name_plural = _('Работы')

    def __str__(self):
        return f'{self.event} - {self.topic} - {self.url}'


class Task(models.Model):
    event = models.ForeignKey(
        Event,
        verbose_name=_('мероприятие'),
        on_delete=models.CASCADE,
    )
    task = RichTextUploadingField(
        verbose_name=_('задание мероприятия'),
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _('Задание мероприятия')
        verbose_name_plural = _('Задания мероприятий')

    def __str__(self):

school-event-management-system/school_event_management_system/events/templates/events/edit_participant_event.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block title %}
    Анкета {{ event.name }} &bull;
{% endblock %}

{% block content %}
    <div class="">
        <h1 class="h1 text-center">{{ event.name }}</h1>
        <div class="d-flex align-items-center py-4 bg-body-tertiary">
            <div class="form w-100 m-auto">
                <div class="nav-scroller py-1 mb-3 border-bottom">
                    <nav class="nav nav-underline justify-content-between">
                        <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_detail' slug=event.slug %}">О событии</a>
                        {% if is_user_participation_of_event or teams or participants %}
                            <a class="nav-item nav-link" href="#">Анкета</a>
                            {% if event.task_set.exists or event.need_presentation %}
                                <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_solution' slug=event.slug %}">Прикрепить работу</a>
                            {% endif %}
                        {% endif %}
                        {% if event.regulations %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.regulations.url }}">Положение</a>
                        {% endif %}
                        {% if event.results %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.results.url }}">Итоги</a>
                        {% endif %}
                        <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_qr_code' slug=event.slug %}">QR-код</a>
                    </nav>
                </div>
                <div>
                    {% if request.user.role != 'ученик' %}
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Выбрать команду или участника
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        {% if request.user.role != 'ученик' %}
                                            <form action="{% url 'edit_participant_event' slug=event.slug %}" method="get">
                                                {% bootstrap_form team_or_participant_form %}
                                                <button class="btn btn-primary w-100 py-2" style="margin-top: 10px;" type="submit">Перейти к форме</button>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                    {% endif %}
                    <form method="POST" action="">
                        {% if participant_id or team_id or is_user_participation_of_event %}
                            {% csrf_token %}
                            {% if event.type == 'Индивидуальное' %}
                                {% bootstrap_form participant_form %}
                            {% else %}
                                {% bootstrap_form team_form %}
                                {% bootstrap_form team_participants_form %}
                            {% endif %}
                            {% bootstrap_form supervisor_form %}
                            {% if event.status == 'Регистрация открыта' %}
                                <button class="btn btn-primary w-100 py-2" style="margin-top: 10px;" type="submit">Изменить анкету</button>
                            {% endif %}
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

school-event-management-system/school_event_management_system/events/templates/events/event_detail.html
{% extends "base.html" %}

{% block title %}
    {{ event.name }} &bull;
{% endblock %}

{% block content %}
    <div class="">
        <h1 class="h1 text-center">{{ event.name }}</h1>
        <div class="d-flex align-items-center py-4 bg-body-tertiary">
            <div class="form w-100 m-auto">
                {% if event.image %}
                    <svg style="margin-bottom: 10px;" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: {{ event.name }}" preserveAspectRatio="xMidYMid slice" focusable="false">
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <image xlink:href="{{ event.image.url }}" width="100%" height="100%" preserveAspectRatio="xMidYMid slice" focusable="false" />
                    </svg>
                {% endif %}
                {% if event.status == 'Регистрация открыта' %}
                    {% if not is_user_participation_of_event or request.user.role != 'ученик' %}
                        {% if event.date_of_ending_registration %}
                            Регистрация заканчивается {{ event.date_of_ending_registration }}<br>
                        {% endif %}
                        <div style="display: flex; justify-content: center;">
                            <a href="{% url 'register_on_event' slug=event.slug %}" class="btn btn-primary w-100 py-2" style="justify-content: center;">Регистрация</a>
                        </div>
                        <br>
                    {% endif %}
                {% endif %}
                <div class="nav-scroller py-1 mb-3 border-bottom">
                    <nav class="nav nav-underline justify-content-between">
                        <a class="nav-item nav-link" href="#">О событии</a>
                        {% if is_user_participation_of_event or teams or participants %}
                            <a class="nav-item nav-link link-body-emphasis" href="{% url 'edit_participant_event' slug=event.slug %}">Анкета</a>
                            {% if event.task_set.exists or event.need_presentation %}
                                <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_solution' slug=event.slug %}">Прикрепить работу</a>
                            {% endif %}
                        {% endif %}
                        {% if event.regulations %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.regulations.url }}">Положение</a>
                        {% endif %}
                        {% if event.results %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.results.url }}">Итоги</a>
                        {% endif %}
                        <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_qr_code' slug=event.slug %}">QR-код</a>
                    </nav>
                </div>
                <div id="ckeditor-display">
                    {{ event.description|safe }}
                </div>
                статус: {{ event.get_status_display }}<br>
                {% if minimum_number_of_team_members == 1 %}
                {% else %}
                {% endif %}
                тип: {{ event.get_type_display }}<br>
                уровень: {{ event.get_stage_display }}<br>

                {% if event.date_of_starting_event %}
                    Дата начала мероприятия: {{ event.date_of_starting_event }}<br>
                {% endif %}
                {% if event.type != 'Индивидуальное' %}
                    Размер команды: от {{ event.minimum_number_of_team_members }} до {{ event.maximum_number_of_team_members }}<br>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

school-event-management-system/school_event_management_system/events/templates/events/event_qr_code.html
{% extends "base.html" %}

{% block title %}
    {{ event.name }} &bull;
{% endblock %}

{% block content %}
    <div class="">
        <h1 class="h1 text-center">{{ event.name }}</h1>
        <div class="d-flex align-items-center py-4 bg-body-tertiary">
            <div class="form w-100 m-auto">
                {% if event.status == 'Регистрация открыта' and not is_user_participation_of_event %}
                    {% if event.date_of_ending_registration %}
                        Регистрация заканчивается {{ event.date_of_ending_registration }}<br>
                    {% endif %}
                    <div style="display: flex; justify-content: center;">
                        <a href="{% url 'register_on_event' slug=event.slug %}" class="btn btn-primary w-100 py-2" style="justify-content: center;">Регистрация</a>
                    </div>
                    <br>
                {% endif %}
                <div class="nav-scroller py-1 mb-3 border-bottom">
                    <nav class="nav nav-underline justify-content-between">
                        <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_detail' slug=event.slug %}">О событии</a>
                        {% if is_user_participation_of_event or teams or participants %}
                            <a class="nav-item nav-link link-body-emphasis" href="{% url 'edit_participant_event' slug=event.slug %}">Анкета</a>
                            {% if event.task_set.exists or event.need_presentation %}
                                <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_solution' slug=event.slug %}">Прикрепить работу</a>
                            {% endif %}
                        {% endif %}
                        {% if event.regulations %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.regulations.url }}">Положение</a>
                        {% endif %}
                        {% if event.results %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.results.url }}">Итоги</a>
                        {% endif %}
                        <a class="nav-item nav-link" href="#">QR-код</a>
                    </nav>
                </div>
                <img src="data:image/png;base64,{{ qr_code }}" class="img-fluid" alt="...">
            </div>
        </div>
    </div>
{% endblock %}

school-event-management-system/school_event_management_system/events/templates/events/event_solution.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block title %}
    Решение {{ event.name }} &bull;
{% endblock %}

{% block content %}
    <div class="">
        <h1 class="h1 text-center">{{ event.name }}</h1>
        <div class="d-flex align-items-center py-4 bg-body-tertiary">
            <div class="form w-100 m-auto">
                <div class="nav-scroller py-1 mb-3 border-bottom">
                    <nav class="nav nav-underline justify-content-between">
                        <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_detail' slug=event.slug %}">О событии</a>
                        {% if is_user_participation_of_event or teams or participants %}
                            <a class="nav-item nav-link link-body-emphasis" href="{% url 'edit_participant_event' slug=event.slug %}">Анкета</a>
                            {% if event.task_set.exists or event.need_presentation %}
                                <a class="nav-item nav-link" href="#">Прикрепить работу</a>
                            {% endif %}
                        {% endif %}
                        {% if event.regulations %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.regulations.url }}">Положение</a>
                        {% endif %}
                        {% if event.results %}
                            <a class="nav-item nav-link link-body-emphasis" href="{{ event.results.url }}">Итоги</a>
                        {% endif %}
                        <a class="nav-item nav-link link-body-emphasis" href="{% url 'event_qr_code' slug=event.slug %}">QR-код</a>
                    </nav>
                </div>
                <div>
                    {% if request.user.role != 'ученик' %}
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                        Выбрать команду или участника
                                    </button>
                                </h2>
                                <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        {% if request.user.role != 'ученик' %}
                                            <form action="{% url 'event_solution' slug=event.slug %}" method="get">
                                                {% bootstrap_form team_or_participant_form %}
                                                <button class="btn btn-primary w-100 py-2" style="margin-top: 10px;" type="submit">Перейти к форме</button>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br>
                    {% endif %}
                    <form method="POST" action="">
                        <div id="ckeditor-display">
                            {{ task.task|safe }}
                        </div>
                        {% csrf_token %}
                        {% if participant_id or team_id or is_user_participation_of_event %}
                            {% bootstrap_form solution_form %}
                            {% if event.status == 'Регистрация открыта' or event.status == 'В процессе' %}
                                <button class="btn btn-primary w-100 py-2" style="margin-top: 10px;" type="submit">Отправить</button>
                            {% endif %}
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

school-event-management-system/school_event_management_system/events/templates/events/events_archive.html
{% extends 'base.html' %}

{% block title %}
    Список мероприятий &bull;
{% endblock %}

{% block content %}
    <h1 class="text-center">Список мероприятий</h1>
    <br>
    <div class="container mx-auto">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Тип</th>
                <th scope="col">Этап</th>
                </tr>
            </thead>
            {% for event in events %}
                <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'event_detail' event.slug %}">{{ event.name }}</a></td>
                        <td>{{ event.get_type_display }}</td>
                        <td>{{ event.get_stage_display }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    </div>
{% endblock %}

school-event-management-system/school_event_management_system/events/templates/events/register_on_event.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block title %}
    Регистрация на {{ event.name }} &bull;
{% endblock %}

{% block content %}
    <div class="d-flex align-items-center py-4 bg-body-tertiary">
        <div class="form w-100 m-auto">
            <form method="POST" class="form w-100 m-auto">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-norma text-center"><a href="{% url 'event_detail' slug=event.slug %}">{{ event.name }}</a></h1>
                {% if event.type == 'Индивидуальное' %}
                    {% bootstrap_form participant_form %}
                {% else %}
                    {% bootstrap_form team_form %}
                    {% bootstrap_form team_participants_form %}
                {% endif %}
                {% bootstrap_form supervisor_form %}
                <button class="btn btn-primary w-100 py-2" style="margin-top: 10px;" type="submit">Зарегистрироваться</button>
            </form>
        </div>
    </div>
{% endblock %}